before_install: []
env:
  global: []
install:
  - 'a() { set -e; return $CI_EXIT; }'
  - "z() { E=$?; CI_EXIT=$E || $CI_EXIT; test $E -eq 0 || echo 'STOP>>>'; }"
  - "zz() { E=$?; test $E -eq 0 && return 0; return $E; }"
  - (a; echo osx setup );z
script:
  - (a; echo osx build );z
  - (a; false );z
  - (a; echo end );zz
after_success:
  - echo SUCCCESS
after_failure:
  - echo FAILURE
git:
  depth: 10
language: objective-c
notifications:
  email: false
matrix:
  fast_finish: true
