before_install: []
env:
  global: []
install:
  - 'a() { set -e; }'
  - "z() { E=$?; test $E -eq 0 && return 0; printf \"\\n\\033[1;31mThe command failed with exit code $?.\\033[0m\"; set -e; return $E; }"
  - (a; echo osx setup );z
script:
  - (a; echo osx build );z
  - (a; false );z
  - (a; echo end );z
after_success:
  - echo SUCCCESS
after_failure:
  - echo FAILURE
git:
  depth: 10
language: objective-c
notifications:
  email: false
matrix:
  fast_finish: true
